-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : mar. 30 mai 2023 à 04:33
-- Version du serveur : 10.4.28-MariaDB
-- Version de PHP : 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `bibliotheque electronique`
--

-- --------------------------------------------------------

--
-- Structure de la table `book`
--

CREATE TABLE `book` (
  `id_book` int(11) NOT NULL,
  `Name_book` varchar(100) NOT NULL,
  `description` varchar(255) NOT NULL,
  `file` longblob NOT NULL,
  `image` longblob NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Déchargement des données de la table `book`
--

INSERT INTO `book` (`id_book`, `Name_book`, `description`, `file`, `image`) VALUES
(32, 'books', '\nIn the CSS code, we add white-space: pre-line; to the .product-description class. This preserves the line breaks generated by the PHP code and allows the text to wrap to the next line every 4 words.\n', 0x6d616e6172202834295f6d65726765642028312920283129202831292e706466, 0x35366266313634346532363366306335623636613332643266666563646563612e706e67202831292e6a7067),
(33, 'book', '\r\nIn the CSS code, we add white-space: pre-line; to the .product-description class. This preserves the line breaks generated by the PHP code and allows the text to wrap to the next line every 4 words.\r\n', 0x6d616e6172202834295f6d65726765642028312920283129202831292e706466, 0x35366266313634346532363366306335623636613332643266666563646563612e706e67202831292e6a7067),
(34, 'book', '\r\nIn the CSS code, we add white-space: pre-line; to the .product-description class. This preserves the line breaks generated by the PHP code and allows the text to wrap to the next line every 4 words.\r\n', 0x6d616e6172202834295f6d65726765642028312920283129202831292e706466, 0x35366266313634346532363366306335623636613332643266666563646563612e706e67202831292e6a7067),
(35, 'book', '\r\nIn the CSS code, we add white-space: pre-line; to the .product-description class. This preserves the line breaks generated by the PHP code and allows the text to wrap to the next line every 4 words.\r\n', 0x6d616e6172202834295f6d65726765642028312920283129202831292e706466, 0x35366266313634346532363366306335623636613332643266666563646563612e706e67202831292e6a7067),
(36, 'book', '\r\nIn the CSS code, we add white-space: pre-line; to the .product-description class. This preserves the line breaks generated by the PHP code and allows the text to wrap to the next line every 4 words.\r\n', 0x6d616e6172202834295f6d65726765642028312920283129202831292e706466, 0x35366266313634346532363366306335623636613332643266666563646563612e706e67202831292e6a7067),
(37, 'book', '\r\nIn the CSS code, we add white-space: pre-line; to the .product-description class. This preserves the line breaks generated by the PHP code and allows the text to wrap to the next line every 4 words.\r\n', 0x6d616e6172202834295f6d65726765642028312920283129202831292e706466, 0x35366266313634346532363366306335623636613332643266666563646563612e706e67202831292e6a7067);

-- --------------------------------------------------------

--
-- Structure de la table `wuser`
--

CREATE TABLE `wuser` (
  `wid` int(7) NOT NULL,
  `wusername` varchar(50) NOT NULL,
  `wemail` varchar(50) NOT NULL,
  `wpassword` varchar(255) NOT NULL,
  `wrole` varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Déchargement des données de la table `wuser`
--

INSERT INTO `wuser` (`wid`, `wusername`, `wemail`, `wpassword`, `wrole`) VALUES
(1, 'admin', 'admin@gmail.com', 'fati2015', 'admin'),
(23, 'sara2001', 'sara@gmail.com', '12345678', 'user'),
(24, 'sara20011', 'sara1@gmail.com', '12345678', 'user');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `book`
--
ALTER TABLE `book`
  ADD PRIMARY KEY (`id_book`);

--
-- Index pour la table `wuser`
--
ALTER TABLE `wuser`
  ADD PRIMARY KEY (`wid`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `book`
--
ALTER TABLE `book`
  MODIFY `id_book` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=38;

--
-- AUTO_INCREMENT pour la table `wuser`
--
ALTER TABLE `wuser`
  MODIFY `wid` int(7) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
